# Default kitty theme — overwritten by theme-switch.sh on first login

background #141218
foreground #E6E0E9
cursor #D0BCFF

selection_background #4F378B
selection_foreground #EADDFF

color0  #211F26
color1  #F2B8B5
color2  #A8C7A0
color3  #E6C77A
color4  #D0BCFF
color5  #CCC2DC
color6  #8ECDE6
color7  #E6E0E9
color8  #2B2930
color9  #F2B8B5
color10 #A8C7A0
color11 #E6C77A
color12 #D0BCFF
color13 #CCC2DC
color14 #8ECDE6
color15 #E6E0E9
