-- Hyprland 0.55+ Lua config

require("theme") -- generated by theme-switch.sh via matugen

-- ── Monitor ────────────────────────────────────────────────────────────────
hl.monitor({ output = "", mode = "highres", position = "auto", scale = 1.25 })

-- ── Environment Variables ──────────────────────────────────────────────────
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GDK_SCALE", "1")

-- ── Autostart ──────────────────────────────────────────────────────────────
hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("~/.config/hypr/scripts/theme-switch.sh")
    hl.exec_cmd("bash -c 'day=$(date +%u); hour=$((10#$(date +%H))); [[ $day -le 5 && $hour -ge 9 && $hour -lt 17 ]] && slack'")
    hl.exec_cmd("blueman-applet")
end)

-- ── Options ────────────────────────────────────────────────────────────────
hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 1,
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = 0,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 8,
            render_power = 2,
            offset = "0 2",
        },
        blur = {
            enabled = true,
            size = 9,
            passes = 4,
            new_optimizations = true,
            xray = false,
            ignore_opacity = true,
            vibrancy = 0.28,
        },
    },

    input = {
        kb_layout = "us",
        follow_mouse = 1,
        float_switch_override_focus = 2,
        sensitivity = 0,
        accel_profile = "flat",
        repeat_rate = 50,
        repeat_delay = 300,
        numlock_by_default = true,
        touchpad = {
            natural_scroll = false,
            tap_to_click = true,
            drag_lock = false,
            disable_while_typing = true,
            clickfinger_behavior = false,
            scroll_factor = 0.5,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        vrr = 1,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        disable_splash_rendering = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        focus_on_activate = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },
})

-- ── Animations ─────────────────────────────────────────────────────────────
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0,    0},    {1,    1}    } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5,  0.5},  {0.75, 1}   } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1,  1}   } })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default"       })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint"  })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, bezier = "easeOutQuint"  })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear"  })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear"  })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick"         })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint"  })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear"  })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear"  })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick"         })

-- ── Window Rules ───────────────────────────────────────────────────────────
hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({ match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false }, no_focus = true })

hl.window_rule({ match = { class = "slack" }, workspace = "5 silent" })

-- Transparency for blur-visible apps
hl.window_rule({ match = { class = "kitty" }, opacity = "0.92 override 0.85 override" })

-- ── Layer Rules ────────────────────────────────────────────────────────────
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "rofi"   }, blur = true, ignore_alpha = 0.5, no_anim = true })

-- ── Keybinds ───────────────────────────────────────────────────────────────

-- Apps
hl.bind("SUPER + SPACE",         hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + E",             hl.dsp.exec_cmd("thunar"))
hl.bind("SUPER + RETURN",        hl.dsp.exec_cmd("rofi -show drun"))
hl.bind("SUPER + L",             hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + N",             hl.dsp.exec_cmd("swaync-client -t"))
hl.bind("SUPER + SHIFT + W",     hl.dsp.exec_cmd("~/.config/hypr/scripts/theme-switch.sh"))

-- Window management
hl.bind("SUPER + C",             hl.dsp.window.close({}))
hl.bind("SUPER + X",             hl.dsp.window.kill({}))
hl.bind("SUPER + M",             hl.dsp.exit())
hl.bind("SUPER + V",             hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + F",             hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind("SUPER + P",             hl.dsp.window.pseudo({ action = "toggle" }))

-- Focus
hl.bind("SUPER + left",          hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + right",         hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + up",            hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + down",          hl.dsp.focus({ direction = "d" }))

-- Move windows
hl.bind("SUPER + CTRL + left",   hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + CTRL + right",  hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + CTRL + up",     hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + CTRL + down",   hl.dsp.window.move({ direction = "d" }))

-- Resize windows
hl.bind("SUPER + ALT + right",   hl.dsp.window.resize({ x =  50, y =   0, relative = true }), { repeating = true })
hl.bind("SUPER + ALT + left",    hl.dsp.window.resize({ x = -50, y =   0, relative = true }), { repeating = true })
hl.bind("SUPER + ALT + up",      hl.dsp.window.resize({ x =   0, y = -50, relative = true }), { repeating = true })
hl.bind("SUPER + ALT + down",    hl.dsp.window.resize({ x =   0, y =  50, relative = true }), { repeating = true })

-- Workspaces
for i = 1, 10 do
    local key = tostring(i % 10)
    hl.bind("SUPER + " .. key,           hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. key,   hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad)
hl.bind("SUPER + S",             hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER + SHIFT + S",     hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through workspaces
hl.bind("SUPER + mouse_down",    hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up",      hl.dsp.focus({ workspace = "e-1" }))

-- Mouse move/resize
hl.bind("SUPER + mouse:272",     hl.dsp.window.drag(),   { mouse = true })
hl.bind("SUPER + mouse:273",     hl.dsp.window.resize(), { mouse = true })

-- Volume keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),  { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),        { repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))

-- Brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { repeating = true })

-- Media
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),        { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),    { locked = true })

-- Screenshots
hl.bind("Print",       hl.dsp.exec_cmd("grim - | tee $HOME/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy --type image/png && notify-send 'Screenshot' 'Fullscreen captured'"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | tee $HOME/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy --type image/png && notify-send 'Screenshot' 'Area captured'"))
hl.bind("CTRL + Print",  hl.dsp.exec_cmd("grim -g \"$(hyprctl -j activewindow | jq -r '\"\\(.at[0]),\\(.at[1]) \\(.size[0])x\\(.size[1])\"')\" - | tee $HOME/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy --type image/png && notify-send 'Screenshot' 'Window captured'"))
