# Default hyprlock config — overwritten by theme-switch.sh on first login

general {
    hide_cursor = true
    ignore_empty_input = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 7
    noise = 0.0117
    contrast = 0.7
    brightness = 0.5
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(938F99ff)
    inner_color = rgba(211F26ff)
    font_color = rgba(D0BCFFff)
    fade_on_empty = false
    placeholder_text = <span foreground="#938F99">Enter Password</span>
    hide_input = false
    rounding = 0
    fail_color = rgba(F2B8B5ff)
    fail_text = <span foreground="#F2B8B5">Auth Failed</span>

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgb(E6E0E9)
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %B %d')"
    color = rgb(938F99)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgb(D0BCFF)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -30
    halign = center
    valign = center
}
